export const ERROR_MESSAGE = {
  USER_NOT_FOUND: "User not found",
  USER_ALREADY_EXIST: "User already exist",
  USER_NOT_EXIST: "User not exist",
  USER_NOT_AUTHORIZED: "User not authorized",
  SERVER_ERROR: "Server is not responding",
  NOT_FOUND: "Not found",
  BAD_REQUEST: "Bad request",
  FORBIDDEN_ACCESS: "Forbidden access",
  UNAUTHORIZED_ACCESS: "Unauthorized access",
  INVALID_CREDENTIALS: "Invalid credentials",
  ALREADY_EXISTS: "Already exists",
  NOTICE_NOT_FOUND: "Notice not found",
  GROUP_NOT_FOUND: "Group not found",
  GROUP_ALREADY_EXIST: "Group already exist",
};
export const RESPONSE_MESSAGE = {
  STUDENT_FETCHED: "Student fetched successfully",
  USER_REGISTERED_SUCCESSFULLY: "User registered successfully",
  USER_UPDATED: "User updated successfully",
  USER_DELETED: "User deleted successfully",
  USER_FETCHED: "User fetched successfully",
  USER_LIST_FETCHED: "User list fetched successfully",
  GROUP_CREATED_SUCCESSFULLY: "Group created successfully",
  GROUP_FETCHED_SUCCESSFULLY: "Group fetched successfully",
  GROUP_UPDATED: "Group updated successfully",
  GROUP_DELETED: "Group deleted successfully",
  GROUP_DELETED_SUCCESSFULLY: "Group deleted successfully",
  GROUP_FETCHED: "Group fetched successfully",
  NOTICE_CREATED_SUCCESSFULLY: "Notice created successfully",
  NOTICES_FETCHED_SUCCESSFULLY: "Notices fetched successfully",
  NOTICE_FETCHED_SUCCESSFULLY: "Notice fetched successfully",
  NOTICE_UPDATED_SUCCESSFULLY: "Notice updated successfully",

  NOTICE_DELETED_SUCCESSFULLY: "Notice deleted successfully",
  MESSAGE_SENT_SUCCESSFULLY: "Message sent successfully",
  MESSAGE_FETCHED_SUCCESSFULLY: "Message fetched successfully",
  MESSAGE_DELETED_SUCCESSFULLY: "Message deleted successfully",
  ATTENDANCE_CREATE: "Attendance marked successfully",
  ATTENDANCE_UPDATE: "Attendance updated successfully",
  FEEDETAILS_CREATE: "FeeDetails created successfully",
  FEEDETAILS_FETCHED: "FeeDetails fetched successfully",
};
export const TYPE_ORM_ERROR_CODE = {
  ER_DUP_ENTRY: "ER_DUP_ENTRY",
};
